import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Arnab Behen Ka Lawda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">  
      <body className={inter.className}>

      <header>
        <Navbar />
      </header>
      <main>
      {children}
      </main>
      </body>
    </html>
  );
}
